import{a as h,S as q,i as c}from"./assets/vendor-CucEYOFD.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();const P="56464018-9d065431ef651fdc70593a5c2";h.defaults.baseURL="https://pixabay.com/api/";async function g(o,r=1){const a={key:P,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15};return(await h.get("",{params:a})).data}const y=document.querySelector(".gallery"),b=document.querySelector(".loader"),d=document.querySelector(".load-more-btn"),M=new q(".gallery a",{captionsData:"alt",captionDelay:250});function L(o){const r=o.map(({webformatURL:a,largeImageURL:i,tags:e,likes:t,views:n,comments:v,downloads:F})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${i}">
          <img class="gallery-image" src="${a}" alt="${e}" />
        </a>
        <div class="info-container">
          <p class="info-item"><b>Likes</b> <span>${t}</span></p>
          <p class="info-item"><b>Views</b> <span>${n}</span></p>
          <p class="info-item"><b>Comments</b> <span>${v}</span></p>
          <p class="info-item"><b>Downloads</b> <span>${F}</span></p>
        </div>
      </li>
    `).join("");y.insertAdjacentHTML("beforeend",r),M.refresh()}function $(){y.innerHTML=""}function w(){b.classList.remove("is-hidden")}function u(){b.classList.add("is-hidden")}function S(){d&&d.classList.remove("is-hidden")}function f(){d&&d.classList.add("is-hidden")}const x=document.querySelector(".search-form"),m=document.querySelector(".load-more-btn");let l="",s=1,p=0;x.addEventListener("submit",E);m&&m.addEventListener("click",O);async function E(o){if(o.preventDefault(),l=o.currentTarget.elements["search-text"].value.trim(),l===""){c.warning({title:"Warning",message:"Please enter a search query.",position:"topRight"});return}s=1,$(),f(),w();try{const r=await g(l,s);if(p=r.totalHits,r.hits.length===0){c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#EF4040",messageColor:"#FFF",closeColor:"#FFF",maxWidth:"432px"}),u();return}L(r.hits),p>s*15&&S()}catch{c.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{u()}}async function O(){s+=1,f(),w();try{const o=await g(l,s);L(o.hits),smoothScroll(),s*15>=p?(f(),c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):S()}catch{c.error({title:"Error",message:"Failed to fetch more images.",position:"topRight"})}finally{u()}}
//# sourceMappingURL=index.js.map
