import{a as y,S as M,i as s}from"./assets/vendor-CucEYOFD.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const R="56464018-9d065431ef651fdc70593a5c2";y.defaults.baseURL="https://pixabay.com/api/";async function b(r,t=1){const a={key:R,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};return(await y.get("",{params:a})).data}const l=document.querySelector(".gallery"),u=document.querySelector(".loader"),f=document.querySelector(".load-more-btn");let p;l&&(p=new M(".gallery a",{captionsData:"alt",captionDelay:250}));function L(r){if(!l)return;const t=r.map(({webformatURL:a,largeImageURL:n,tags:e,likes:o,views:c,comments:F,downloads:P})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${n}">
          <img class="gallery-image" src="${a}" alt="${e}" />
        </a>
        <div class="info-container">
          <p class="info-item"><b>Likes</b> <span>${o}</span></p>
          <p class="info-item"><b>Views</b> <span>${c}</span></p>
          <p class="info-item"><b>Comments</b> <span>${F}</span></p>
          <p class="info-item"><b>Downloads</b> <span>${P}</span></p>
        </div>
      </li>
    `).join("");l.insertAdjacentHTML("beforeend",t),p&&p.refresh()}function $(){l&&(l.innerHTML="")}function w(){u&&u.classList.remove("is-hidden")}function S(){u&&u.classList.add("is-hidden")}function v(){f&&f.classList.remove("is-hidden")}function m(){f&&f.classList.add("is-hidden")}const x=document.querySelector(".form"),g=document.querySelector(".load-more-btn");let d="",i=1,h=0;const q=15;x.addEventListener("submit",B);g&&g.addEventListener("click",E);async function B(r){if(r.preventDefault(),d=r.currentTarget.elements["search-text"].value.trim(),d===""){s.warning({title:"Warning",message:"Please enter a search query.",position:"topRight"});return}i=1,$(),m(),w();try{const t=await b(d,i);if(h=t.totalHits,t.hits.length===0){s.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#EF4040",messageColor:"#FFF",closeColor:"#FFF",maxWidth:"432px"});return}L(t.hits),h>i*q?v():s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch{s.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{S()}}async function E(){i+=1,m(),w();try{const r=await b(d,i);L(r.hits),C(),i*q>=h?(m(),s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):v()}catch{s.error({title:"Error",message:"Failed to fetch more images.",position:"topRight"})}finally{S()}}function C(){const r=document.querySelector(".gallery-item");if(r){const{height:t}=r.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
